title: CCIE Enterprise Infrastructure v1.1
description: CCIE Enterprise Infrastructure v1.1 Study Notes

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
heading_anchors: true
nav_enabled: true
